version: '3'
services:
  trading_bot:
    image: "alphainsider/trading_bot:test"
    build:
      context: ./
      args:
        - ENVIRONMENT=production
    environment:
      ALPHAINSIDER_API_KEY: ${ALPHAINSIDER_API_KEY}
      STRATEGY_ID: ${STRATEGY_ID}
      MARGIN_MULTIPLIER: ${MARGIN_MULTIPLIER}
      BUFFER_AMOUNT: ${BUFFER_AMOUNT}
      ALPACA_KEY: ${ALPACA_KEY}
      ALPACA_SECRET: ${ALPACA_SECRET}
      ALPACA_ACCOUNT_TYPE: ${ALPACA_ACCOUNT_TYPE}
    volumes:
      - ./:/app/trading_bot
      - /app/trading_bot/node_modules
    command: bash -c "npm run dev"