version: '3'
services:
  server:
    image: "alphainsider/trading_bot:test"
    build:
      context: .
      args:
        - ENVIRONMENT=development
    environment:
      ALPHAINSIDER_API_KEY: ${ALPHAINSIDER_API_KEY}
      STRATEGY_ID: ${STRATEGY_ID}
      MARGIN_MULTIPLIER: ${MARGIN_MULTIPLIER}
      BUFFER_AMOUNT: ${BUFFER_AMOUNT}
      ALPACA_KEY: ${ALPACA_KEY}
      ALPACA_SECRET: ${ALPACA_SECRET}
      ALPACA_ACCOUNT_TYPE: ${ALPACA_ACCOUNT_TYPE}
    volumes:
      - ./lib:/app/server/lib
      - ./public:/app/server/public
      - ./express.js:/app/server/express.js
      - /app/server/node_modules
    command: npm run dev