version: '3'
services:
  db:
    image: postgres:10.14-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - 127.0.0.1:5432:5432

  server:
    image: "alphainsider/trading_bot:test"
    build:
      context: .
      args:
        - NODE_ENV=development
    environment:
      DATABASE_URL: ${DATABASE_URL}
      USER_PASSWORD: ${USER_PASSWORD}
    volumes:
      - ./database:/app/server/database
      - ./lib:/app/server/lib
      - ./public:/app/server/public
      - ./express.js:/app/server/express.js
      - /app/server/node_modules
    ports:
      - 127.0.0.1:3000:3000
    command: npm run dev