name: _build_electron

on:
  workflow_call:
    secrets:
      SIGNING_WINDOWS_CERT_KEY:
        required: true
      SIGNING_WINDOWS_CERT_PASS:
        required: true
      SIGNING_MACOS_CERT_KEY:
        required: true
      SIGNING_MACOS_CERT_PASS:
        required: true
      SIGNING_MACOS_NOTARY_KEY:
        required: true
      SIGNING_MACOS_NOTARY_ID:
        required: true
      SIGNING_MACOS_NOTARY_ISSUER:
        required: true

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    
    steps:
      #TODO: setup node
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 12
      
      # setup python
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      # get app artifacts
      - name: Get app artifacts
        uses: actions/download-artifact@v4
        with:
          name: built-app
      
      # (macOS) set notary key details
      - name: (macOS) Set notary key details
        if: startsWith(matrix.os, 'macos')
        run: |
          mkdir -p ~/private_keys/
          echo "${{ secrets.SIGNING_MACOS_NOTARY_KEY }}" | base64 -d > ~/private_keys/AuthKey_${{ secrets.SIGNING_MACOS_NOTARY_ID }}.p8
          echo "API_KEY_ID=${{ secrets.SIGNING_MACOS_NOTARY_ID }}" >> $GITHUB_ENV
          echo "API_KEY_ISSUER_ID=${{ secrets.SIGNING_MACOS_NOTARY_ISSUER }}" >> $GITHUB_ENV
      
      # build electron and attach artifacts to release
      - name: Build electron and attach artifacts to release
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          # Windows signing
          #TODO: windows_certs: ${{ secrets.SIGNING_WINDOWS_CERT_KEY }}
          #TODO: windows_certs_password: ${{ secrets.SIGNING_WINDOWS_CERT_PASS }}
          # MacOS signing
          mac_certs: ${{ secrets.SIGNING_MACOS_CERT_KEY }}
          mac_certs_password: ${{ secrets.SIGNING_MACOS_CERT_PASS }}