name: Build Electron App

on:
  workflow_call:

jobs:
  build_electron:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-11, windows-latest]
    steps:
      # get app artifacts
      - name: Get app artifacts
        uses: actions/download-artifact@v4
        with:
          name: built-app
      
      # build electron
      - name: Build electron app
        shell: bash
        run: |
          npm install
          npm run electron-make
      
      # setup python
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      # upload artifacts
      - name: Upload electron artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-electron-${{ matrix.os }}
          path: ./out/make