name: _push_docker

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
        description: 'Version Number (eg: 0.0.0)'
      DOCKER_USERNAME:
        type: 'string'
        required: true
      DOCKER_TOKEN:
        type: 'string'
        required: true

jobs:
  # push docker
  push_docker:
    runs-on: ubuntu-latest
    steps:
      # get app artifacts
      - name: Get app artifacts
        uses: actions/download-artifact@v4
        with:
          name: built-app
          path: app
      
      #TODO: remove
      - name: test
        shell: bash
        run: |
          echo "Docker username test secret: ${{ github.event.inputs.DOCKER_USERNAME }}"
      
      # login to docker hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.event.inputs.DOCKER_USERNAME }}
          password: ${{ github.event.inputs.DOCKER_TOKEN }}
      
      # build and push docker image
      #TODO: add latest (alphainsider/trading_bot:latest)
#      - name: Build and push Docker image
#        uses: docker/build-push-action@v2
#        with:
#          context: ./app
#          push: true
#          tags: |
#            alphainsider/trading_bot:${{ github.event.inputs.version }}