name: _push_docker

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
        description: 'Version Number (eg: 0.0.0)'

jobs:
  # push docker
  push_docker:
    runs-on: ubuntu-latest
    steps:
      # checkout server
      - name: Checkout trading_bot
        uses: actions/checkout@v4
        with:
          repository: AlphaInsider/trading_bot
          ref: master
      
      # get app artifacts
      - name: Get app artifacts
        uses: actions/download-artifact@v4
        with:
          name: built-app
          path: app
      
      # login to docker hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      # build and push docker image
      #TODO: add latest (alphainsider/trading_bot:latest)
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./app
          push: true
          tags: |
            alphainsider/trading_bot:${{ github.event.inputs.version }}