name: New Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: 'Version Number (eg: 0.0.0)'

jobs:
  # merge master
  merge_master:
    uses: ./.github/workflows/_merge_master.yml@dev
    with:
      version: ${{ github.event.inputs.version }}
  
  # build app
  build_app:
    needs: merge_master
    uses: ./.github/workflows/_build_app.yml@dev
  
  # build electron
  build_electron:
    needs: build_app
    uses: ./.github/workflows/_build_electron.yml@dev
  
  # new release
  new_release:
    needs: build_electron
    runs-on: ubuntu-latest
    steps:
      # checkout master
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: master
      
      # create release
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: Release v${{ github.event.inputs.version }}
          draft: true #TODO: set to false
      
      # get electron artifacts
      - name: Get electron artifacts
        uses: actions/download-artifact@v4
        with:
          path: release_artifacts
          pattern: built-electron-*
          merge-multiple: true
      
      # upload release artifacts
      - name: Upload release artifacts
        shell: bash
        run: |
          find ./release_artifacts -type f | while read FILE; do
            echo "Uploading ${FILE}..."
            curl \
              -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Content-Type: $(file -b --mime-type "${FILE}")" \
              --data-binary @"${FILE}" \
              "${{ steps.create_release.outputs.upload_url }}?name=$(basename "${FILE}")"
          done