name: NEW_RELEASE

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: 'Version Number (eg: 0.0.0)'
      push_docker:
        type: boolean
        required: true
        description: 'Push to docker'
        default: true

permissions:
  contents: write

jobs:
  # update version
  update_version:
    uses: ./.github/workflows/_update_version.yml
    with:
      version: ${{ github.event.inputs.version }}
  
  # new release
  new_release:
    needs: update_version
    runs-on: ubuntu-latest
    steps:
      # create release
      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target_commitish: master
          tag_name: v${{ github.event.inputs.version }}
          name: Release v${{ github.event.inputs.version }}
          generate_release_notes: true
          draft: true
  
  # build app
  build_app:
    needs: new_release
    uses: ./.github/workflows/_build_app.yml
  
  # build electron
  build_electron:
    needs: build_app
    uses: ./.github/workflows/_build_electron.yml
    secrets:
      SIGNING_WINDOWS_CERT_KEY: ${{ secrets.SIGNING_WINDOWS_CERT_KEY }}
      SIGNING_WINDOWS_CERT_PASS: ${{ secrets.SIGNING_WINDOWS_CERT_PASS }}
      SIGNING_MACOS_CERT_KEY: ${{ secrets.SIGNING_MACOS_CERT_KEY }}
      SIGNING_MACOS_CERT_PASS: ${{ secrets.SIGNING_MACOS_CERT_PASS }}
      SIGNING_MACOS_NOTARY_KEY: ${{ secrets.SIGNING_MACOS_NOTARY_KEY }}
      SIGNING_MACOS_NOTARY_ID: ${{ secrets.SIGNING_MACOS_NOTARY_ID }}
      SIGNING_MACOS_NOTARY_ISSUER: ${{ secrets.SIGNING_MACOS_NOTARY_ISSUER }}
  
  # push docker
  push_docker:
    if: ${{ github.event.inputs.push_docker == 'true' }}
    needs: build_electron
    uses: ./.github/workflows/_push_docker.yml
    with:
      version: ${{ github.event.inputs.version }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}