name: TEST

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: 'Version Number (eg: 0.0.0)'

permissions:
  contents: write

jobs:
  # test
  test:
    runs-on: ubuntu-latest
    steps:
      # test
      - name: test
        shell: bash
        run: |
          echo "Github TEST secret: ${{ secrets.DOCKER_USERNAME }}"
  
  # push docker
  push_docker:
    needs: test
    uses: ./.github/workflows/_push_docker.yml@dev
    with:
      version: ${{ github.event.inputs.version }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_token: ${{ secrets.DOCKER_TOKEN }}